export const PlayerPosition = [
  { value: 'GK', label: 'GK - Goalkeeper' },
  { value: 'CB', label: 'CB - Center Back' },
  { value: 'LB', label: 'LB - Left Back' },
  { value: 'RB', label: 'RB - Right Back' },
  { value: 'LWB', label: 'LWB - Left Wing Back' },
  { value: 'RWB', label: 'RWB - Right Wing Back' },
  { value: 'CDM', label: 'CDM - Defensive Mid' },
  { value: 'CM', label: 'CM - Central Mid' },
  { value: 'CAM', label: 'CAM - Attacking Mid' },
  { value: 'LM', label: 'LM - Left Mid' },
  { value: 'RM', label: 'RM - Right Mid' },
  { value: 'LW', label: 'LW - Left Wing' },
  { value: 'RW', label: 'RW - Right Wing' },
  { value: 'ST', label: 'ST - Striker' },
  { value: 'CF', label: 'CF - Center Forward' },
]
