// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sports.Api.Database;

#nullable disable

namespace Sports.Api.Migrations
{
    [DbContext(typeof(SportsDbContext))]
    partial class SportsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sports.Shared.Entities.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Premier League"
                        },
                        new
                        {
                            Id = 2,
                            Name = "La Liga"
                        });
                });

            modelBuilder.Entity("Sports.Shared.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalPasses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayTeamId = 2,
                            HomeTeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            AwayTeamId = 3,
                            HomeTeamId = 2
                        },
                        new
                        {
                            Id = 3,
                            AwayTeamId = 4,
                            HomeTeamId = 3
                        },
                        new
                        {
                            Id = 4,
                            AwayTeamId = 5,
                            HomeTeamId = 4
                        },
                        new
                        {
                            Id = 5,
                            AwayTeamId = 6,
                            HomeTeamId = 5
                        },
                        new
                        {
                            Id = 6,
                            AwayTeamId = 7,
                            HomeTeamId = 6
                        },
                        new
                        {
                            Id = 7,
                            AwayTeamId = 8,
                            HomeTeamId = 7
                        },
                        new
                        {
                            Id = 8,
                            AwayTeamId = 1,
                            HomeTeamId = 8
                        },
                        new
                        {
                            Id = 9,
                            AwayTeamId = 3,
                            HomeTeamId = 1
                        },
                        new
                        {
                            Id = 10,
                            AwayTeamId = 4,
                            HomeTeamId = 2
                        },
                        new
                        {
                            Id = 11,
                            AwayTeamId = 5,
                            HomeTeamId = 3
                        },
                        new
                        {
                            Id = 12,
                            AwayTeamId = 6,
                            HomeTeamId = 4
                        },
                        new
                        {
                            Id = 13,
                            AwayTeamId = 7,
                            HomeTeamId = 5
                        },
                        new
                        {
                            Id = 14,
                            AwayTeamId = 8,
                            HomeTeamId = 6
                        },
                        new
                        {
                            Id = 15,
                            AwayTeamId = 1,
                            HomeTeamId = 7
                        },
                        new
                        {
                            Id = 16,
                            AwayTeamId = 2,
                            HomeTeamId = 8
                        },
                        new
                        {
                            Id = 17,
                            AwayTeamId = 4,
                            HomeTeamId = 1
                        },
                        new
                        {
                            Id = 18,
                            AwayTeamId = 5,
                            HomeTeamId = 2
                        },
                        new
                        {
                            Id = 19,
                            AwayTeamId = 6,
                            HomeTeamId = 3
                        },
                        new
                        {
                            Id = 20,
                            AwayTeamId = 7,
                            HomeTeamId = 4
                        },
                        new
                        {
                            Id = 21,
                            AwayTeamId = 8,
                            HomeTeamId = 5
                        },
                        new
                        {
                            Id = 22,
                            AwayTeamId = 1,
                            HomeTeamId = 6
                        },
                        new
                        {
                            Id = 23,
                            AwayTeamId = 2,
                            HomeTeamId = 7
                        },
                        new
                        {
                            Id = 24,
                            AwayTeamId = 3,
                            HomeTeamId = 8
                        },
                        new
                        {
                            Id = 25,
                            AwayTeamId = 5,
                            HomeTeamId = 1
                        },
                        new
                        {
                            Id = 26,
                            AwayTeamId = 6,
                            HomeTeamId = 2
                        },
                        new
                        {
                            Id = 27,
                            AwayTeamId = 7,
                            HomeTeamId = 3
                        },
                        new
                        {
                            Id = 28,
                            AwayTeamId = 8,
                            HomeTeamId = 4
                        },
                        new
                        {
                            Id = 29,
                            AwayTeamId = 1,
                            HomeTeamId = 5
                        },
                        new
                        {
                            Id = 30,
                            AwayTeamId = 2,
                            HomeTeamId = 6
                        },
                        new
                        {
                            Id = 31,
                            AwayTeamId = 3,
                            HomeTeamId = 7
                        },
                        new
                        {
                            Id = 32,
                            AwayTeamId = 4,
                            HomeTeamId = 8
                        },
                        new
                        {
                            Id = 33,
                            AwayTeamId = 6,
                            HomeTeamId = 1
                        },
                        new
                        {
                            Id = 34,
                            AwayTeamId = 7,
                            HomeTeamId = 2
                        },
                        new
                        {
                            Id = 35,
                            AwayTeamId = 8,
                            HomeTeamId = 3
                        },
                        new
                        {
                            Id = 36,
                            AwayTeamId = 1,
                            HomeTeamId = 4
                        },
                        new
                        {
                            Id = 37,
                            AwayTeamId = 2,
                            HomeTeamId = 5
                        },
                        new
                        {
                            Id = 38,
                            AwayTeamId = 3,
                            HomeTeamId = 6
                        },
                        new
                        {
                            Id = 39,
                            AwayTeamId = 4,
                            HomeTeamId = 7
                        },
                        new
                        {
                            Id = 40,
                            AwayTeamId = 5,
                            HomeTeamId = 8
                        },
                        new
                        {
                            Id = 41,
                            AwayTeamId = 7,
                            HomeTeamId = 1
                        },
                        new
                        {
                            Id = 42,
                            AwayTeamId = 8,
                            HomeTeamId = 2
                        },
                        new
                        {
                            Id = 43,
                            AwayTeamId = 1,
                            HomeTeamId = 3
                        },
                        new
                        {
                            Id = 44,
                            AwayTeamId = 2,
                            HomeTeamId = 4
                        },
                        new
                        {
                            Id = 45,
                            AwayTeamId = 3,
                            HomeTeamId = 5
                        },
                        new
                        {
                            Id = 46,
                            AwayTeamId = 4,
                            HomeTeamId = 6
                        },
                        new
                        {
                            Id = 47,
                            AwayTeamId = 5,
                            HomeTeamId = 7
                        },
                        new
                        {
                            Id = 48,
                            AwayTeamId = 6,
                            HomeTeamId = 8
                        },
                        new
                        {
                            Id = 49,
                            AwayTeamId = 8,
                            HomeTeamId = 1
                        },
                        new
                        {
                            Id = 50,
                            AwayTeamId = 1,
                            HomeTeamId = 2
                        },
                        new
                        {
                            Id = 51,
                            AwayTeamId = 2,
                            HomeTeamId = 3
                        },
                        new
                        {
                            Id = 52,
                            AwayTeamId = 3,
                            HomeTeamId = 4
                        },
                        new
                        {
                            Id = 53,
                            AwayTeamId = 4,
                            HomeTeamId = 5
                        },
                        new
                        {
                            Id = 54,
                            AwayTeamId = 5,
                            HomeTeamId = 6
                        },
                        new
                        {
                            Id = 55,
                            AwayTeamId = 6,
                            HomeTeamId = 7
                        },
                        new
                        {
                            Id = 56,
                            AwayTeamId = 7,
                            HomeTeamId = 8
                        },
                        new
                        {
                            Id = 57,
                            AwayTeamId = 2,
                            HomeTeamId = 1
                        },
                        new
                        {
                            Id = 58,
                            AwayTeamId = 3,
                            HomeTeamId = 2
                        },
                        new
                        {
                            Id = 59,
                            AwayTeamId = 4,
                            HomeTeamId = 3
                        },
                        new
                        {
                            Id = 60,
                            AwayTeamId = 5,
                            HomeTeamId = 4
                        },
                        new
                        {
                            Id = 61,
                            AwayTeamId = 6,
                            HomeTeamId = 5
                        },
                        new
                        {
                            Id = 62,
                            AwayTeamId = 7,
                            HomeTeamId = 6
                        },
                        new
                        {
                            Id = 63,
                            AwayTeamId = 8,
                            HomeTeamId = 7
                        },
                        new
                        {
                            Id = 64,
                            AwayTeamId = 1,
                            HomeTeamId = 8
                        },
                        new
                        {
                            Id = 65,
                            AwayTeamId = 2,
                            HomeTeamId = 1
                        },
                        new
                        {
                            Id = 66,
                            AwayTeamId = 3,
                            HomeTeamId = 2
                        },
                        new
                        {
                            Id = 67,
                            AwayTeamId = 4,
                            HomeTeamId = 3
                        },
                        new
                        {
                            Id = 68,
                            AwayTeamId = 5,
                            HomeTeamId = 4
                        },
                        new
                        {
                            Id = 69,
                            AwayTeamId = 6,
                            HomeTeamId = 5
                        },
                        new
                        {
                            Id = 70,
                            AwayTeamId = 7,
                            HomeTeamId = 6
                        },
                        new
                        {
                            Id = 71,
                            AwayTeamId = 8,
                            HomeTeamId = 7
                        },
                        new
                        {
                            Id = 72,
                            AwayTeamId = 1,
                            HomeTeamId = 8
                        },
                        new
                        {
                            Id = 73,
                            AwayTeamId = 3,
                            HomeTeamId = 1
                        },
                        new
                        {
                            Id = 74,
                            AwayTeamId = 4,
                            HomeTeamId = 2
                        },
                        new
                        {
                            Id = 75,
                            AwayTeamId = 5,
                            HomeTeamId = 3
                        },
                        new
                        {
                            Id = 76,
                            AwayTeamId = 6,
                            HomeTeamId = 4
                        },
                        new
                        {
                            Id = 77,
                            AwayTeamId = 7,
                            HomeTeamId = 5
                        },
                        new
                        {
                            Id = 78,
                            AwayTeamId = 8,
                            HomeTeamId = 6
                        },
                        new
                        {
                            Id = 79,
                            AwayTeamId = 1,
                            HomeTeamId = 7
                        },
                        new
                        {
                            Id = 80,
                            AwayTeamId = 2,
                            HomeTeamId = 8
                        },
                        new
                        {
                            Id = 81,
                            AwayTeamId = 4,
                            HomeTeamId = 1
                        },
                        new
                        {
                            Id = 82,
                            AwayTeamId = 5,
                            HomeTeamId = 2
                        },
                        new
                        {
                            Id = 83,
                            AwayTeamId = 6,
                            HomeTeamId = 3
                        },
                        new
                        {
                            Id = 84,
                            AwayTeamId = 7,
                            HomeTeamId = 4
                        },
                        new
                        {
                            Id = 85,
                            AwayTeamId = 8,
                            HomeTeamId = 5
                        },
                        new
                        {
                            Id = 86,
                            AwayTeamId = 1,
                            HomeTeamId = 6
                        },
                        new
                        {
                            Id = 87,
                            AwayTeamId = 2,
                            HomeTeamId = 7
                        },
                        new
                        {
                            Id = 88,
                            AwayTeamId = 3,
                            HomeTeamId = 8
                        },
                        new
                        {
                            Id = 89,
                            AwayTeamId = 5,
                            HomeTeamId = 1
                        },
                        new
                        {
                            Id = 90,
                            AwayTeamId = 6,
                            HomeTeamId = 2
                        },
                        new
                        {
                            Id = 91,
                            AwayTeamId = 7,
                            HomeTeamId = 3
                        },
                        new
                        {
                            Id = 92,
                            AwayTeamId = 8,
                            HomeTeamId = 4
                        },
                        new
                        {
                            Id = 93,
                            AwayTeamId = 1,
                            HomeTeamId = 5
                        },
                        new
                        {
                            Id = 94,
                            AwayTeamId = 2,
                            HomeTeamId = 6
                        },
                        new
                        {
                            Id = 95,
                            AwayTeamId = 3,
                            HomeTeamId = 7
                        },
                        new
                        {
                            Id = 96,
                            AwayTeamId = 4,
                            HomeTeamId = 8
                        },
                        new
                        {
                            Id = 97,
                            AwayTeamId = 6,
                            HomeTeamId = 1
                        },
                        new
                        {
                            Id = 98,
                            AwayTeamId = 7,
                            HomeTeamId = 2
                        },
                        new
                        {
                            Id = 99,
                            AwayTeamId = 8,
                            HomeTeamId = 3
                        },
                        new
                        {
                            Id = 100,
                            AwayTeamId = 1,
                            HomeTeamId = 4
                        });
                });

            modelBuilder.Entity("Sports.Shared.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "David Raya",
                            Position = "GK",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ben White",
                            Position = "RB",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "William Saliba",
                            Position = "CB",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gabriel Magalhaes",
                            Position = "CB",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Oleksandr Zinchenko",
                            Position = "LB",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Declan Rice",
                            Position = "CDM",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Thomas Partey",
                            Position = "CM",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Martin Odegaard",
                            Position = "CAM",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Bukayo Saka",
                            Position = "RW",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 10,
                            Name = "Gabriel Martinelli",
                            Position = "LW",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 11,
                            Name = "Kai Havertz",
                            Position = "ST",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Ederson",
                            Position = "GK",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Kyle Walker",
                            Position = "RB",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Ruben Dias",
                            Position = "CB",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "John Stones",
                            Position = "CB",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 16,
                            Name = "Josko Gvardiol",
                            Position = "LB",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 17,
                            Name = "Rodri",
                            Position = "CDM",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 18,
                            Name = "Mateo Kovacic",
                            Position = "CM",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 19,
                            Name = "Kevin De Bruyne",
                            Position = "CAM",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bernardo Silva",
                            Position = "RW",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 21,
                            Name = "Phil Foden",
                            Position = "LW",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 22,
                            Name = "Erling Haaland",
                            Position = "ST",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 23,
                            Name = "Alisson Becker",
                            Position = "GK",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 24,
                            Name = "Trent Alexander-Arnold",
                            Position = "RB",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 25,
                            Name = "Virgil van Dijk",
                            Position = "CB",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 26,
                            Name = "Ibrahima Konate",
                            Position = "CB",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 27,
                            Name = "Andrew Robertson",
                            Position = "LB",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 28,
                            Name = "Ryan Gravenberch",
                            Position = "CDM",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 29,
                            Name = "Alexis Mac Allister",
                            Position = "CM",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 30,
                            Name = "Dominik Szoboszlai",
                            Position = "CAM",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 31,
                            Name = "Mohamed Salah",
                            Position = "RW",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 32,
                            Name = "Luis Diaz",
                            Position = "LW",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 33,
                            Name = "Darwin Nunez",
                            Position = "ST",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 34,
                            Name = "Robert Sanchez",
                            Position = "GK",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 35,
                            Name = "Reece James",
                            Position = "RB",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 36,
                            Name = "Wesley Fofana",
                            Position = "CB",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 37,
                            Name = "Levi Colwill",
                            Position = "CB",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 38,
                            Name = "Marc Cucurella",
                            Position = "LB",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 39,
                            Name = "Moises Caicedo",
                            Position = "CDM",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 40,
                            Name = "Enzo Fernandez",
                            Position = "CM",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 41,
                            Name = "Christopher Nkunku",
                            Position = "CAM",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 42,
                            Name = "Cole Palmer",
                            Position = "RW",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 43,
                            Name = "Mykhailo Mudryk",
                            Position = "LW",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 44,
                            Name = "Nicolas Jackson",
                            Position = "ST",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 45,
                            Name = "Thibaut Courtois",
                            Position = "GK",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 46,
                            Name = "Dani Carvajal",
                            Position = "RB",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 47,
                            Name = "Antonio Rudiger",
                            Position = "CB",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 48,
                            Name = "David Alaba",
                            Position = "CB",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 49,
                            Name = "Ferland Mendy",
                            Position = "LB",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 50,
                            Name = "Eduardo Camavinga",
                            Position = "CDM",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 51,
                            Name = "Federico Valverde",
                            Position = "CM",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 52,
                            Name = "Jude Bellingham",
                            Position = "CAM",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 53,
                            Name = "Rodrygo",
                            Position = "RW",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 54,
                            Name = "Vinicius Junior",
                            Position = "LW",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 55,
                            Name = "Kylian Mbappe",
                            Position = "ST",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 56,
                            Name = "Marc-Andre ter Stegen",
                            Position = "GK",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 57,
                            Name = "Jules Kounde",
                            Position = "RB",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 58,
                            Name = "Ronald Araujo",
                            Position = "CB",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 59,
                            Name = "Andreas Christensen",
                            Position = "CB",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 60,
                            Name = "Alejandro Balde",
                            Position = "LB",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 61,
                            Name = "Frenkie de Jong",
                            Position = "CDM",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 62,
                            Name = "Pedri",
                            Position = "CM",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 63,
                            Name = "Gavi",
                            Position = "CAM",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 64,
                            Name = "Raphinha",
                            Position = "RW",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 65,
                            Name = "Lamine Yamal",
                            Position = "LW",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 66,
                            Name = "Robert Lewandowski",
                            Position = "ST",
                            TeamId = 6
                        },
                        new
                        {
                            Id = 67,
                            Name = "Jan Oblak",
                            Position = "GK",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 68,
                            Name = "Nahuel Molina",
                            Position = "RB",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 69,
                            Name = "Jose Gimenez",
                            Position = "CB",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 70,
                            Name = "Axel Witsel",
                            Position = "CB",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 71,
                            Name = "Reinildo Mandava",
                            Position = "LB",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 72,
                            Name = "Rodrigo De Paul",
                            Position = "CDM",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 73,
                            Name = "Koke",
                            Position = "CM",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 74,
                            Name = "Antoine Griezmann",
                            Position = "CAM",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 75,
                            Name = "Angel Correa",
                            Position = "RW",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 76,
                            Name = "Samuel Lino",
                            Position = "LW",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 77,
                            Name = "Julian Alvarez",
                            Position = "ST",
                            TeamId = 7
                        },
                        new
                        {
                            Id = 78,
                            Name = "Orjan Nyland",
                            Position = "GK",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 79,
                            Name = "Jesus Navas",
                            Position = "RB",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 80,
                            Name = "Loic Bade",
                            Position = "CB",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 81,
                            Name = "Tanguy Nianzou",
                            Position = "CB",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 82,
                            Name = "Marcos Acuna",
                            Position = "LB",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 83,
                            Name = "Nemanja Gudelj",
                            Position = "CDM",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 84,
                            Name = "Fernando Reges",
                            Position = "CM",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 85,
                            Name = "Ivan Rakitic",
                            Position = "CAM",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 86,
                            Name = "Dodi Lukebakio",
                            Position = "RW",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 87,
                            Name = "Lucas Ocampos",
                            Position = "LW",
                            TeamId = 8
                        },
                        new
                        {
                            Id = 88,
                            Name = "Youssef En-Nesyri",
                            Position = "ST",
                            TeamId = 8
                        });
                });

            modelBuilder.Entity("Sports.Shared.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeagueId = 1,
                            Name = "Arsenal"
                        },
                        new
                        {
                            Id = 2,
                            LeagueId = 1,
                            Name = "Manchester City"
                        },
                        new
                        {
                            Id = 3,
                            LeagueId = 1,
                            Name = "Liverpool"
                        },
                        new
                        {
                            Id = 4,
                            LeagueId = 1,
                            Name = "Chelsea"
                        },
                        new
                        {
                            Id = 5,
                            LeagueId = 2,
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 6,
                            LeagueId = 2,
                            Name = "Barcelona"
                        },
                        new
                        {
                            Id = 7,
                            LeagueId = 2,
                            Name = "Atletico Madrid"
                        },
                        new
                        {
                            Id = 8,
                            LeagueId = 2,
                            Name = "Sevilla"
                        });
                });

            modelBuilder.Entity("Sports.Shared.Entities.Match", b =>
                {
                    b.HasOne("Sports.Shared.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sports.Shared.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("Sports.Shared.Entities.Player", b =>
                {
                    b.HasOne("Sports.Shared.Entities.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Sports.Shared.Entities.Team", b =>
                {
                    b.HasOne("Sports.Shared.Entities.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("Sports.Shared.Entities.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Sports.Shared.Entities.Team", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
